// <auto-generated />
namespace E_CommerceLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PublisherBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PublisherBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202308130433076_PublisherBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
